unbind r
bind r source-file ~/.config/tmux/tmux.conf

set -g prefix C-space
bind C-space send-prefix

set -g status-style bg=black

bind R source-file ~/.config/tmux/tmux.conf \; \
display-message "Tmux Reload..."

set -g allow-passthrough on

set-option -g status-keys vi		
set-window-option -g mode-keys vi
set -g status-right  ''

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set -g renumber-windows on

# Add decause of Higher escape-time 
set-option -sg escape-time 10

# Add because autoread may not work
set-option -g focus-events on

# Add because color support not detected
set-option -ga terminal-overrides "${TERM}:RGB"

# force block cursor
set -g terminal-features 'xterm*:Ss=1:Se=2'

# or explicitly send sequence on attach
set -g @cursor_block 'printf "\e[2 q"'
