--ignore-gpu-blocklist
--enable-gpu-rasterization
--enable-zero-copy
--enable-features=AcceleratedVideoDecodeLinuxGL,AcceleratedVideoDecodeLinuxZeroCopyGL,AcceleratedVideoEncoder,CanvasOopRasterization,VaapiIgnoreDriverChecks,UseMultiPlaneFormatForHardwareVideo
--ozone-platform-hint=auto

--disable-font-subpixel-positioning
--force-device-scale-factor=2

--gtk-version=4
--enable-features=TouchpadOverscrollHistoryNavigation
--enable-wayland-ime
--disable-features=ExtensionManifestV2Unsupported
