background {
	path = ~/assets/adventure_time.png
    blur_passes = 1
    blur_size = 1
    zindex = 0
}

# Weather
label {
  text = cmd[update:1000] ~/.config/hypr/scripts/weather_cache.sh
  color = rgba(255, 255, 255, 0.8)
  font_size = 10
  font_family = JetBrainsMonoNerdFont Bold
  position = 40, -150
  halign = left
  valign = top
}

# Week
label {
  text = cmd[update:0] echo "$(date +"%A")"
  color = rgba(255, 255, 255, 0.8)
  font_size = 32
  font_family = Noto Serif Ethiopic, Bold
  position = 40, -50
  halign = left
  valign = top
}

# Date
label {
  text = cmd[update:0] echo "$(date +"%d")"
  color = rgba(255, 107, 107, 1.0)
  font_size = 16
  font_family = SF Pro Rounded, Black
  position = 40, -100
  halign = left
  valign = top
}

# Month
label {
  text = cmd[update:0] echo "$(date +"%B")"
  color = rgba(255, 255, 255, 0.8)
  font_size = 16
  font_family = SF Pro Rounded, Black
  position = 70, -100
  halign = left
  valign = top
}

# Time hours
label {
  shadow_size = 2
  shadow_passes = 7
  shadow_color = rgb(0,0,0)
  shadow_boost = 1.2
  text = cmd[update:1000] echo -e "$(date +"%H")"
  color = rgb(172, 166, 180)
  font_size = 140
  font_family = Noto Serif Ethiopic, Bold
  position = -15, 180
  halign = center
  valign = center
}

# Time minutes
label {
  shadow_size = 2
  shadow_passes = 7
  shadow_color = rgb(0,0,0)
  shadow_boost = 1.2
  text = cmd[update:1000] echo -e "$(date +"%M")"
  color = rgb(255, 255, 255)
  font_size = 120
  font_family = Noto Serif Ethiopic, Bold
  position = 15, 45
  halign = center
  valign = center
}

# Password fild
input-field {
	shadow_size = 2
	shadow_passes = 4
	shadow_color = rgb(0,0,0)
	shadow_boost = 2
    size = 210, 50
    outline_thickness = 2
    outer_color = rgba(80, 80, 80, 1) rgba(0, 0, 0, 0) 240deg
    inner_color = rgba(0, 0, 0, 0.15)
    font_color = rgba(255, 255, 255, 1)
    fade_on_empty = false
    rounding = 20
    dots_size = 0.15
    dots_spacing = 0.35
    dots_center = true
    check_color = rgba(80, 80, 80, 1) rgba(0, 0, 0, 0) 120deg
    placeholder_text = <span foreground="##ffffff80">   Password</span>
    hide_input = false
    font_family = Adwaita Sans, Bold
    position = 0, -420
    halign = center
    valign = center
    zindex = 1
}
