# Backside of wallpaper
background {
    monitor =
    blur_size = 2
    blur_passes = 4
    path = ~/.config/hypr/late-night-smoking-fujiwara-tofu-store-initial-d-moewalls-com.mp4
}


# DATE
label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%A, %B %d")"
  color = rgba(255, 255, 255, 0.8)
  font_size = 11
  font_family = JetBrainsMonoNerdFontMono, Bold
  position = 875, 525
  halign = center
  valign = center
}

# TIME
label {
  monitor =
  shadow_size = 2
  shadow_passes = 7
  shadow_color = rgb(0,0,0)
  shadow_boost = 1.2
  text = cmd[update:1000] echo -e "$(date +"%H")"
  color = rgba(172, 166, 180, 1)
  font_size = 120
  font_family = Adwaita Sans, Heavy
  position = -15, 180
  halign = center
  valign = center
}

label {
  monitor =
  shadow_size = 2
  shadow_passes = 7
  shadow_color = rgb(0,0,0)
  shadow_boost = 1.2
  text = cmd[update:1000] echo -e "$(date +"%M")"
  color = rgba(255, 255, 255, 1)
  font_size = 120
  font_family = Adwaita Sans, Heavy
  position = 15, 45
  halign = center
  valign = center
}

# FrontSide of wallpaper
background {
    monitor =
    zindex = 1
#    keep_aspect_ratio = true
#    rounding = 0
#    border_size = 0
#	shadow_size = 2
#	shadow_passes = 6
#	shadow_color = rgb(0,0,0)
#	shadow_boost = 1
    path = ~/.config/hypr/fg2.png
}


# PSWD PROMPT
input-field {
    monitor =
	shadow_size = 2
	shadow_passes = 4
	shadow_color = rgb(0,0,0)
	shadow_boost = 2
    size = 210, 50
    outline_thickness = 2
    outer_color = rgba(80, 80, 80, 1) rgba(0, 0, 0, 0) 240deg
    inner_color = rgba(0, 0, 0, 0.15)
    font_color = rgba(255, 255, 255, 1)
    fade_on_empty = false
    rounding = 20
    dots_size = 0.15
    dots_spacing = 0.35
    dots_center = true
    check_color = rgba(80, 80, 80, 1) rgba(0, 0, 0, 0) 120deg
    placeholder_text = <span foreground="##ffffff80">   Password</span>
    hide_input = false
    font_family = Adwaita Sans, Bold
    position = 0, -420
    halign = center
    valign = center
    zindex = 1
}
