$noto_font = Noto Serif Ethiopic, Bold
$sf_pro_font = SF Pro Rounded, Heavy

background {
    path = ~/assets/otters.png
    blur_passes = 1
    blur_size = 1
    zindex = 0
}

# Weather glass
shape {
    size = 400, 190
    color = rgba(48, 83, 94, 0.4)

    rounding = 28

    border_size = 2
    border_color = rgba(152, 179, 195, 1) rgba(1, 1, 1, 0.1) 90deg

    position = -140, -76

    halign = right
    valign = top
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

# Weather
label {
    text = cmd[update:1000] ~/.config/hypr/scripts/weather_cache.sh

    color = rgb(1, 1, 1)
    font_size = 11
    font_family = JetBrains Mono NL Nerd Font Propo SemiBold

    position = -180, -90
    halign = right
    valign = top

    shadow_size = 1
    shadow_passes = 1
    shadow_color = rgb(10, 15, 13)
    shadow_boost = 0.8

    zindex = 1
}

label {
    shadow_size = 1
    shadow_passes = 1
    shadow_color = rgb(10, 15, 13)
    shadow_boost = 0.65

    text = cmd[update:0] echo "$(date +"%A")"
    color = rgba(217, 228, 231, 0.90)

    font_size = 32
    font_family = $noto_font

    position = 40, -50
    halign = left
    valign = top
}

label {
    shadow_size = 1
    shadow_passes = 1
    shadow_color = rgb(10, 15, 13)
    shadow_boost = 0.65

    text = cmd[update:0] echo "$(date +"%d")"
    color = rgb(127, 140, 83)

    font_size = 16
    font_family = $sf_pro_font

    position = 40, -100
    halign = left
    valign = top
}

label {
    shadow_size = 1
    shadow_passes = 1
    shadow_color = rgb(10, 15, 13)
    shadow_boost = 0.65

    text = cmd[update:0] echo "$(date +"%B")"
    color = rgba(217, 228, 231, 0.85)

    font_size = 16
    font_family = $sf_pro_font

    position = 75, -100
    halign = left
    valign = top
}

label {
    shadow_size = 2
    shadow_passes = 2
    shadow_color = rgb(10, 15, 13)
    shadow_boost = 0.70

	text = $TIME
    color = rgb(48, 83, 94)

    font_size = 140
    font_family = $sf_pro_font

    position = 0, 180
    halign = center
    valign = center
}

#Name
label {

	text = <span font_family="SF Pro Rounded, Heavy" foreground="##D9E4E7B3">$USER</span>

    font_size = 28
    font_family = $sf_pro_font

    position = 20, 30
    halign = center
    valign = center
}

#PC Icon
label {

	text = <span font_family="SF Pro Rounded, Heavy" foreground="##D9E4E7B3"><span font_family="Material Symbols Rounded">laptop_mac</span></span>
    #color = rgb(48, 83, 94)

    font_size = 27
    font_family = $sf_pro_font

    position = -55, 27
    halign = center
    valign = center
}

input-field {

    outline_thickness = 2

    outer_color = rgba(152, 179, 195, 0.6) rgba(1, 1, 1, 0.6) 240deg

    inner_color = rgba(0, 0, 0, 0.4)

    font_color = rgba(217, 228, 231, 0.8)

    fade_on_empty = false

    rounding = 28

    dots_size = 0.15
    dots_spacing = 0.35
    dots_center = true

    check_color = rgba(127, 140, 83, 0.4) rgba(48, 83, 94, 0.4) 120deg

	size = 4%, 5%
	placeholder_text =  passkey password_2 key
    hide_input = false

	font_family = Material Symbols Rounded
    position = 0, -10
    halign = center
    valign = top

    zindex = 1
	fail_text = <span font_family="SF Pro Rounded, Heavy" foreground="##D9E4E7B3"><i>$FAIL <b>($ATTEMPTS)</b></i></span>

	check_text = <span font_family="SF Pro Rounded, Heavy" foreground="##D9E4E7B3">Authenticating...</span>
}
