@include "picom-animations.conf"

backend = "xrender"   
vsync = true	     
dithered-present = false
dbus = false
shadow = false      
fading = false     
blur-background = false   
blur-background-frame = false
blur-background-fixed = false
corner-radius = 0
round-borders = 0
frame-opacity = 1.0
transition-length = 0
size-transition = false
detect-rounded-corners = false
use-ewmh-active-win = false
detect-transient = false
detect-client-opacity = false


rules = (
	{
	  match = "window_type = 'popup_menu' || "
			  "window_type = 'utility' || "
			  "window_type = 'tooltip' || "
			  "window_type = 'dock'";
	  animations = (
		  {
			triggers = ["show"];

			opacity = {
			  curve = "linear";
			  duration = 0.18;
			  start = 0;
			  end = "window-raw-opacity";
			};

			scale-x = {
			  curve = "cubic-bezier(0.25, 0.1, 0.25, 1.0)";
			  duration = 0.18;
			  start = 0.5; 
			  end = 1;
			};
			scale-y = "scale-x";

			offset-x = "(1 - scale-x) / 2 * window-width";
			offset-y = "(1 - scale-y) / 2 * window-height";
		  },

		  {
			triggers = ["hide"];

			opacity = {
			  curve = "linear";
			  duration = 0.15;
			  start = "window-raw-opacity-before";
			  end = 0;
			};

			scale-x = {
			  curve = "cubic-bezier(0.7, 0, 0.3, 1)"; 
			  duration = 0.15;
			  start = 1;
			  end = 0.5; 
			};
			scale-y = "scale-x";

			offset-x = "(1 - scale-x) / 2 * window-width";
			offset-y = "(1 - scale-y) / 2 * window-height";
		  })
	},

	{
	  match = "window_type = 'notification'";
	  animations = ({
			triggers = ["open", "show"];

			opacity = {
			  curve = "linear";
			  duration = 0.2;
			  start = 0;
			  end = "window-raw-opacity";
			};

			offset-x = {
			  curve = "cubic-bezier(0.4, 0.2, 0.2, 1)"; 
			  duration = 0.2;
			  start = 200;
			  end = 0;
			};

			scale-x = 1;
			scale-y = 1;

		  }, {
			triggers = ["hide","close"];

			opacity = {
			  curve = "linear";
			  duration = 0.2;
			  start = "window-raw-opacity-before";
			  end = 0;
			};

			offset-x = {
			  curve = "cubic-bezier(0.4, 0.2, 0.2, 1)";
			  duration = 0.2;
			  start = 0;
			  end = 200;
			};

			scale-x = 1;
			scale-y = 1;

		  });
	}
)

