# Minimal effects to save power

backend = "xrender"   
vsync = true	     
dithered-present = false
dbus = false
shadow = false      
fading = false     
blur-background = false   
blur-background-frame = false
blur-background-fixed = false
corner-radius = 0
round-borders = 0
frame-opacity = 1.0
inactive-opacity = 1.0
inactive-dim = 0.0
transition-length = 0
size-transition = false
detect-rounded-corners = false
use-ewmh-active-win = false
mark-wmwin-focused = false
mark-ovredir-focused = false
detect-transient = false
detect-client-opacity = false

log-level = "warn"
opacity-rule = ["100:class_g = 'awesome'"];

opacity-rule = ["100:class_g = 'awesome'"];
rules: (
		{ match = "window_type = 'dock'"; blur-background = false; },
		@include "picom-animations.conf"
	   )
