@include "picom-animations.conf"

#################################
#       General Settings        #
#################################

# Specify the backend to use: `xrender`, `glx`, or `egl`.
#
# Default: "xrender"
backend = "xrender"

# Use higher precision during rendering, and apply dither when presenting the
# rendered screen. Reduces banding artifacts, but may cause performance
# degradation. Only works with OpenGL.
dithered-present = false;

# Enable/disable VSync.
#
# Default: false
vsync = true;

# Try to detect windows with rounded corners and don't consider them
# shaped windows. The accuracy is not very high, unfortunately.
#
# Has nothing to do with `corner-radius`.
#
# Default: false
# detect-rounded-corners = true;

# Detect '_NET_WM_WINDOW_OPACITY' on client windows, useful for window managers
# not passing '_NET_WM_WINDOW_OPACITY' of client windows to frame windows.
#
# Default: false
# detect-client-opacity = true;

# Use EWMH '_NET_ACTIVE_WINDOW' to determine currently focused window,
# rather than listening to 'FocusIn'/'FocusOut' event. May be more accurate,
# provided that the WM supports it.
#
# Default: false
use-ewmh-active-win = true

# Use 'WM_TRANSIENT_FOR' to group windows, and consider windows
# in the same group focused at the same time.
#
# Default: false
detect-transient = true;

fading = true;

fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 3
# Use of damage information for rendering. This cause the only the part of the
# screen that has actually changed to be redrawn, instead of the whole screen
# every time. Should improve performance.
#
# Default: false
use-damage = true;
rules = (
	{
	  match = "window_type = 'dock' || window_type = 'popup_menu' || window_type = 'utility' || window_type = 'tooltip'";
	  animations = (
		  {
			triggers = ["show"];

			opacity = {
			  curve = "linear";
			  duration = 0.18;
			  start = 0;
			  end = "window-raw-opacity";
			};

			scale-x = {
			  curve = "cubic-bezier(0.25, 0.1, 0.25, 1.0)";
			  duration = 0.18;
			  start = 0.5; 
			  end = 1;
			};
			scale-y = "scale-x";

			offset-x = "(1 - scale-x) / 2 * window-width";
			offset-y = "(1 - scale-y) / 2 * window-height";
		  },

		  {
			triggers = ["hide"];

			opacity = {
			  curve = "linear";
			  duration = 0.15;
			  start = "window-raw-opacity-before";
			  end = 0;
			};

			scale-x = {
			  curve = "cubic-bezier(0.7, 0, 0.3, 1)"; 
			  duration = 0.15;
			  start = 1;
			  end = 0.5; 
			};
			scale-y = "scale-x";

			offset-x = "(1 - scale-x) / 2 * window-width";
			offset-y = "(1 - scale-y) / 2 * window-height";
		  })
	},

	{
	  match = "window_type = 'notification'";
	  animations = ({
			triggers = ["open", "show"];

			opacity = {
			  curve = "linear";
			  duration = 0.2;
			  start = 0;
			  end = "window-raw-opacity";
			};

			offset-x = {
			  curve = "cubic-bezier(0.4, 0.2, 0.2, 1)"; 
			  duration = 0.2;
			  start = 200;
			  end = 0;
			};

			scale-x = 1;
			scale-y = 1;

		  }, {
			triggers = ["hide","close"];

			opacity = {
			  curve = "linear";
			  duration = 0.2;
			  start = "window-raw-opacity-before";
			  end = 0;
			};

			offset-x = {
			  curve = "cubic-bezier(0.4, 0.2, 0.2, 1)";
			  duration = 0.2;
			  start = 0;
			  end = 200;
			};

			scale-x = 1;
			scale-y = 1;

		  });
	}
)

