#################################
#           Corners             #
#################################

corner-radius = 12;
round-borders = 1;

#################################
#     Performance Optimized     #
#################################

backend = "glx";

vsync = true;

refresh-rate = 0;

use-damage = true;

mark-wmwin-focused = false;
mark-ovredir-focused = false;
detect-rounded-corners = false;
detect-client-opacity = false;
detect-transient = false;
detect-client-leader = false;

glx-no-stencil = true;
glx-no-rebind-pixmap = true;

shadow = false;

#################################
#       Fading (Disabled)       #
#################################

fading = false;

#################################
#   Transparency/Opacity        #
#################################

inactive-opacity = 1.0;
frame-opacity = 1.0;
inactive-opacity-override = false;

opacity-rule = [];

#################################
#     Background-Blurring       #
#################################

blur-background = false;
blur-background-frame = false;
blur-background-fixed = false;

#################################
#       General Settings        #
#################################


experimental-backends = false;


log-level = "error";

xrender-sync-fence = false;

blur= {
  method = "dual_kawase";
  size = 10;
  strength = 6; 
  deviation = 2.5;
}

rules= (
	{ match = "window_type = 'dock'"; blur-background = false; },
	@include "picom-animations.conf"
	)

