@include "picom-animations.conf"

#################################
#           Corners             #
#################################

corner-radius = 12;
round-borders = 1;

#################################
#     Performance Optimized     #
#################################

backend = "glx";
# backend = "egl";
vsync = true;
use-damage = true;

refresh-rate = 0;

# unredir-if-possible = true;
# unredir-if-possible-delay = 50;

mark-wmwin-focused = false;
mark-ovredir-focused = false;
detect-rounded-corners = false;
detect-client-opacity = false;
detect-transient = false;
detect-client-leader = false;

glx-no-stencil = true;
glx-no-rebind-pixmap = true;

shadow = false;

#################################
#       Fading (Disabled)       #
#################################

fading = false;

#################################
#   Transparency/Opacity        #
#################################

inactive-opacity = 1.0;
frame-opacity = 1.0;
inactive-opacity-override = false;

opacity-rule = [];

#################################
#     Background-Blurring       #
#################################

blur-background = false;
blur-background-frame = false;
blur-background-fixed = false;

#################################
#       General Settings        #
#################################
log-level = "error";

blur= {
  method = "dual_kawase";
  size = 10;
  strength = 6; 
  deviation = 2.5;
}

rules = (
	{
	  match = "window_type = 'dock' || window_type = 'popup_menu' || window_type = 'utility' || window_type = 'tooltip'";
	  blur-background = false;
	  animations = (
		  {
			triggers = ["show"];

			opacity = {
			  curve = "linear";
			  duration = 0.18;
			  start = 0;
			  end = "window-raw-opacity";
			};

			scale-x = {
			  curve = "cubic-bezier(0.25, 0.1, 0.25, 1.0)";
			  duration = 0.18;
			  start = 0.5; 
			  end = 1;
			};
			scale-y = "scale-x";

			offset-x = "(1 - scale-x) / 2 * window-width";
			offset-y = "(1 - scale-y) / 2 * window-height";
		  },

		  {
			triggers = ["hide"];

			opacity = {
			  curve = "linear";
			  duration = 0.15;
			  start = "window-raw-opacity-before";
			  end = 0;
			};

			scale-x = {
			  curve = "cubic-bezier(0.7, 0, 0.3, 1)"; 
			  duration = 0.15;
			  start = 1;
			  end = 0.5; 
			};
			scale-y = "scale-x";

			offset-x = "(1 - scale-x) / 2 * window-width";
			offset-y = "(1 - scale-y) / 2 * window-height";
		  })
	},

	{
	  match = "window_type = 'notification'";
	  animations = ({
			triggers = ["open", "show"];

			opacity = {
			  curve = "linear";
			  duration = 0.2;
			  start = 0;
			  end = "window-raw-opacity";
			};

			offset-x = {
			  curve = "cubic-bezier(0.4, 0.2, 0.2, 1)"; 
			  duration = 0.2;
			  start = 200;
			  end = 0;
			};

			scale-x = 1;
			scale-y = 1;

		  }, {
			triggers = ["hide","close"];

			opacity = {
			  curve = "linear";
			  duration = 0.2;
			  start = "window-raw-opacity-before";
			  end = 0;
			};

			offset-x = {
			  curve = "cubic-bezier(0.4, 0.2, 0.2, 1)";
			  duration = 0.2;
			  start = 0;
			  end = 200;
			};

			scale-x = 1;
			scale-y = 1;

		  });
	}
)

