#################################
#           Fading              #
#################################

fading = true;
fade-in-step = 0.05;
fade-out-step = 0.05;
fade-exclude = ["class_g = 'flameshot'"]

#################################
#           Corners             #
#################################

corner-radius = 12;
round-borders = 1;

#################################
#       General Settings        #
#################################

backend = "glx"
dithered-present = false;
vsync = true;
shadow = false;
detect-rounded-corners = true;
detect-client-opacity = true;
detect-client-leader = true;
detect-transient = true;
transparent-clipping = false

wintypes: {
  popup_menu = {  opacity = 1; };
  notification = { opacity = 1; };
  dropdown_menu = { opacity = 1; }
};

#################################
#             Rules             #
#################################

blur: {
		method = "dual_kawase";
		size = 10;
		strength = 5;
		deviation = 2.5;
	  }

rules: (
		{
		match = "window_type = 'dock'";
		blur-background = false;
		},
		@include "picom-animations.conf"
	   )
