rules = (
	{
	  match = "window_type = 'dock' || window_type = 'popup_menu' || window_type = 'utility' || window_type = 'tooltip'";
	  animations = (
		  {
			triggers = ["show"];

			opacity = {
			  curve = "linear";
			  duration = 0.18;
			  start = 0;
			  end = "window-raw-opacity";
			};

			scale-x = {
			  curve = "cubic-bezier(0.25, 0.1, 0.25, 1.0)";
			  duration = 0.18;
			  start = 0.5; 
			  end = 1;
			};
			scale-y = "scale-x";

			offset-x = "(1 - scale-x) / 2 * window-width";
			offset-y = "(1 - scale-y) / 2 * window-height";
		  },

		  {
			triggers = ["hide"];

			opacity = {
			  curve = "linear";
			  duration = 0.15;
			  start = "window-raw-opacity-before";
			  end = 0;
			};

			scale-x = {
			  curve = "cubic-bezier(0.7, 0, 0.3, 1)"; 
			  duration = 0.15;
			  start = 1;
			  end = 0.5; 
			};
			scale-y = "scale-x";

			offset-x = "(1 - scale-x) / 2 * window-width";
			offset-y = "(1 - scale-y) / 2 * window-height";
		  })
	},

	{
	  match = "window_type = 'notification'";
	  animations = (
			{
			  triggers = ["open","show"];
			  scale-x = {
				curve = "cubic-bezier(1,0,0.2,1.2)";
				duration = 0.3;
				start = 0; 
				end = 1;
			  };
			  scale-y = "scale-x";

			  offset-x = 1;
			  offset-y = 1;
			}
		  );
	},

	{
	  match = "!name && window_type = 'normal' || class_i = 'xfce4-screensaver'";
	  animations = ({ triggers = ["open", "close", "show", "hide", "geometry"]});
	},

	{
	  match = "name";
	  animations = (
		  {
			triggers = ["open"];
			scale-x = {
			  curve = "cubic-bezier(0.05,0.9,0.1,1.05)";
			  duration = 0.3;
			  start = 0; 
			  end = 1;
			};
			scale-y = "scale-x";

			offset-x = "(1 - scale-x) / 2 * window-width";
			offset-y = "(1 - scale-y) / 2 * window-height";
		  },

		  {
			triggers = ["show"];
			opacity = {
			  curve = "linear";
			  duration = 0.2;
			  start = 0;
			  end = 1;
			};
			offset-x = {
			  curve = "cubic-bezier(0,0.6,0,1.2);"; 
			  duration = 0.3;
			  start = -1000;
			  end = 1;
			};
			scale-x = 1;
			scale-y = 1;
		  },

		  {
			triggers = ["geometry"];
			scale-x = {
			  curve = "cubic-bezier(0.05, 0.9, 0.1, 1.05)";
			  duration = 0.4;
			  start = "window-width-before / window-width";
			  end = 1;
			};
			scale-y = {
			  curve = "cubic-bezier(0.05, 0.9, 0.1, 1.05)";
			  duration = 0.4;
			  start = "window-height-before / window-height";
			  end = 1;
			};
			offset-x = {
			  curve = "cubic-bezier(0.05, 0.9, 0.1, 1.05)";
			  duration = 0.4;
			  start = "window-x-before - window-x";
			  end = 0;
			};
			offset-y = {
			  curve = "cubic-bezier(0.05, 0.9, 0.1, 1.05)";
			  duration = 0.4;
			  start = "window-y-before - window-y";
			  end = 0;
			};
		  },
		);
	},
  )
