animations = (
    {
      triggers = ["open"];
      opacity = {
        curve = "linear";
        duration = 0.15;
        start = 0.9;
        end = "window-raw-opacity";
      };

      scale-x = {
        curve = "cubic-bezier(0.25, 0.1, 0.25, 1.0)";
        duration = 0.15;
        start = 0.5; 
        end = 1;
      };
      scale-y = "scale-x";

      offset-x = "(1 - scale-x) / 2 * window-width";
      offset-y = "(1 - scale-y) / 2 * window-height";
      
    },

    {
      triggers = ["close"];
      opacity = {
        curve = "linear";
        duration = 0.15;
        start = "window-raw-opacity-before";
        end = 0;
      };

      scale-x = {
        curve = "cubic-bezier(0.7, 0, 0.3, 1)"; 
        duration = 0.15;
        start = 1;
        end = 0.5; 
      };
      scale-y = "scale-x";

      offset-x = "(1 - scale-x) / 2 * window-width";
      offset-y = "(1 - scale-y) / 2 * window-height";
      
    },

    {
      triggers = ["show"];
      opacity = {
        curve = "linear";
        duration = 0.15;
        start = 0;
        end = "window-raw-opacity";
      };
      offset-x = {
        curve = "cubic-bezier(0.4, 0.2, 0.2, 1)"; 
        duration = 0.15;
        start = -200;
        end = 0;
      };
      scale-x = 1;
      scale-y = 1;
    },

    # {
    #   triggers = ["hide"];
    #   opacity = {
    #     curve = "linear";
    #     duration = 0.2;
    #     start = "window-raw-opacity-before";
    #     end = 0;
    #   };
    #   offset-x = {
    #     curve = "cubic-bezier(0.4, 0.2, 0.2, 1)";
    #     duration = 0.2;
    #     start = 0;
    #     end = -200;
    #   };
    #   scale-x = 1;
    #   scale-y = 1;
    # },

	{
      triggers = ["geometry"];
      scale-x = {
        curve = "cubic-bezier(0.05, 0.9, 0.1, 1.05)";
        duration = 0.15;
        start = "window-width-before / window-width";
        end = 1;
      };
      scale-y = {
        curve = "cubic-bezier(0.05, 0.9, 0.1, 1.05)";
        duration = 0.15;
        start = "window-height-before / window-height";
        end = 1;
      };
      offset-x = {
        curve = "cubic-bezier(0.05, 0.9, 0.1, 1.05)";
        duration = 0.15;
        start = "window-x-before - window-x";
        end = 0;
      };
      offset-y = {
        curve = "cubic-bezier(0.05, 0.9, 0.1, 1.05)";
        duration = 0.15;
        start = "window-y-before - window-y";
        end = 0;
      };
    },
  )
